### ISSUE TITLE
Regarding missing destructor in FluidSolver

### ISSUE THREAD

**Issue by mmmovania** [tunabrain/incremental-fluids#2]
Hi,
  Just wanted to point out that there is a memory leak in the FluidSolver. The constructor allocates _d, _u, _v, _r and _p but there is no destructor that deallocates them. This is in 0-MatrixLess project thats where I have started at the moment. There should be a destructor for FluidSolver like so

`
~FluidSolver() {
   delete _d; 
   delete _u;
   delete _v;
   delete [] _r;
   delete [] _p;
}
`

**Comment by tunabrain** [comment]
You're right! It looks like I got sloppy halfway through the first file and didn't add proper destructors to most classes. It should be fixed now.

Thanks!
